typography_spectrum: 0.9227166147902608
color:
  brandStrength: 0.7225596357602626
  lightness: 0.8202220289967954
  saturation: 0.7824584301561117
  rhythmicContrast: 0.8973096658010036
  brandColors:
    - '#4A4E53'
    - '#FFFFFF'
    - '#000000'
    - '#B3B3B3'
    - '#D61C7D'
layout_spectrum: 0.6721962802112103
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c73cd706-aefa-4cf7-8d6d-bb4b3d50e3f4.jpg
name: 'Dobrodošli na spletnih straneh Odvetniške pisarne '
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0b49d047-49cb-4abf-9cfb-1778d0bcba1b.jpg
title: Primec & Lah
description: ''
